[ML_MODEL] refactor: change model to elasticnet regressor
pdGruby/pricepy pull request #54
Opened 2023-12-28 15:40 UTC by ArturMakowski

- changed model to elasticnet regressor with L1 and L2 regularization (got around 96k mse) 

![image](https://github.com/pdGruby/pricepy/assets/94056689/27c0a6c7-280e-4822-99ce-46cbbd539fcd)

- added hyperparams tuning method
- added docs
- formatted the code with black

2024-01-06 01:30 UTC, pdGruby requested changes
Please, see the comments regarding docstrings.

**Question:** does ElasticSearch return linear results? I mean, if we change any of the parameters slightly, will the predicted result also change (as it is in case of Linear Regression - smooth changes)?

2024-01-06 01:30 UTC, pdGruby commented on ml_model/pricepy_model.py
> +        """Get data from the database."""
In my opinion, the docstring here is useless - the purpose of the method is explained by its name. 

We should create docstrings only for the methods with complex logic or for the methods that will be used in other parts of the code by developers. This method will only be used by the PricepyModel class, so there is no need of docstring creation.

2024-01-06 01:30 UTC, pdGruby commented on ml_model/pricepy_model.py
> +        """Preprocess data."""
Same, useless docstring.

2024-01-06 01:30 UTC, pdGruby commented on ml_model/pricepy_model.py
> +        """Hyperparameter tuning with GridSearchCV. It saves the best parameters into self.best_params attribute."""
Useless docstring

2024-01-06 01:30 UTC, pdGruby commented on ml_model/pricepy_model.py
> +        """Fit the model with the best parameters if those exist. Else, fit the model with default parameters."""
IMO useless docstring, but not that much as the previous ones

2024-01-06 01:30 UTC, pdGruby commented on ml_model/pricepy_model.py
> +        """Training pipeline with data download, preprocessing, hyperparameter tuning, fitting and evaluation."""
Useless

2024-01-06 01:30 UTC, pdGruby commented on ml_model/pricepy_model.py
> +        """
This is okay, since the 'predict' method is used in other parts of the code

2024-01-06 01:30 UTC, pdGruby commented on ml_model/pricepy_model.py
> +        """Evaluate the model with cross-validation and save the evaluation metrics into self.rmse, self.mae and self.r2 attributes."""
Useless

2024-01-06 01:30 UTC, pdGruby commented on ml_model/pricepy_model.py
> +        """Save the model into the database."""
Useless

2024-01-06 01:30 UTC, pdGruby commented on ml_model/pricepy_model.py
> +        """Load the latest model from the database."""
Useless

2024-01-06 11:51 UTC, ArturMakowski commented
> Please, see the comments regarding docstrings.
> 
> **Question:** does ElasticSearch return linear results? I mean, if we change any of the parameters slightly, will the predicted result also change (as it is in case of Linear Regression - smooth changes)?

ElasticNet (not ElasticSearch) returns linear results, just like Linear Regression. It is a linear regression with L1 and L2 regularization. Also, I addressed docstrings issues.

2024-01-07 00:09 UTC, pdGruby approved these changes

2024-01-07 00:10 UTC, merged